# Config
home: false  # True : Set home as latest post, False : Set home as an index

# Header
menu:
  Archives: /archives
rss: /atom.xml
background: https://raw.githubusercontent.com/maywzh/imagebed/master/img/alexandre-nishimura-427272-unsplash%20copy.jpg # Header Background Image

# Library
fancybox: true

# Widget
# Widget List : category, tag, archive, recent_posts
widgets:
- tag
- category
- recent_posts

# Google Analytics
ga_id : UA-119246999-1